// ╔══════════════════════════════════════════════════════════════════════════════╗
// ║  AD ENGINE — "one prompt replaces your agency"                                 ║
// ║                                                                              ║
// ║  From a brand + brief, Opus derives the highest-intent audience NICHES (this   ║
// ║  is where Opus adds value: strategy + copy), each with a hook angle, a ready    ║
// ║  video prompt (in a marketing format), and cold-outreach copy — plus a         ║
// ║  strategist report. Video VARIANTS are then generated by the DIRECT engine      ║
// ║  (pixels → one model, no pipeline). Planning uses the configured model; videos ║
// ║  cost — so generation is opt-in to protect spend.                              ║
// ╚══════════════════════════════════════════════════════════════════════════════╝

import { callAIJSON } from '../ai/deepseek-client';
import type { VideoBrandCtx } from './types';

export interface AdNiche {
  name: string;
  audience: string;
  pain: string;
  angle: string;
  /** Which proven angle category `angle` uses: pain|outcome|social-proof|curiosity|comparison|urgency|identity|contrarian. */
  angleType: string;
  /** Marketing Studio format key (ugc|tv-spot|hyper-motion|unboxing|product-review|demo|tutorial|cinematic|wild-card). */
  format: string;
  /** A vivid, ready text-to-video prompt for this niche's ad. */
  videoPrompt: string;
  /** Short cold-outreach copy (DM/email) for this niche. */
  outreach: string;
  /** Path to the generated video variant, when generation was requested. */
  video?: string;
}

export interface AdPlan {
  niches: AdNiche[];
  report: string;
}

const BRAIN = `You are a senior performance-marketing strategist. From a brand + brief, derive the highest-intent AUDIENCE NICHES to target with short-form video ads — each a distinct, real, reachable segment with its own hook angle. Ground every angle in ONE of these proven categories (pick the best fit per niche, don't blend them): pain point ("stop wasting time on X"), outcome ("achieve Y in Z days"), social proof ("join N who already..."), curiosity ("the X secret..."), comparison ("unlike X, we do Y"), urgency ("limited time..."), identity ("built for [specific role]"), or contrarian ("why [common practice] doesn't work"). Use ONLY real facts about the brand; NEVER invent statistics, prices, spend figures, follower counts, ad-spend rankings, or testimonials. If you don't know a number, stay qualitative — specific and concrete beats vague, but a real specific claim beats a fabricated number every time. Return STRICT JSON only.`;

const clamp = (n: number | undefined, lo: number, hi: number, def: number) =>
  Math.max(lo, Math.min(hi, Math.round(Number(n) || def)));

/**
 * Plan an ad campaign: N audience niches, each with angle + a ready video prompt +
 * outreach copy, plus a strategist report. No video is generated here (that's the
 * direct engine's job and remains opt-in through the configured model router.
 */
export async function planAdEngine(
  ctx: VideoBrandCtx,
  brief: string,
  opts: { niches?: number } = {},
): Promise<AdPlan> {
  const n = clamp(opts.niches, 1, 6, 3);
  const ask = `BRAND: ${ctx.name}
PALETTE: ${ctx.colors.join(', ')}
BRAND INFO (use ONLY these real facts — invent nothing): ${ctx.info || '(infer conservatively from the brand name)'}
BRIEF: ${brief || '(general growth via short-form video ads)'}

Derive the ${n} best audience niches to target with short-form video ads. For each, pick the marketing FORMAT that fits (one of: ugc, tv-spot, hyper-motion, unboxing, product-review, demo, tutorial, cinematic, wild-card). Return JSON:
{
  "niches": [
    {
      "name": "short niche label",
      "audience": "who exactly (demographic + mindset)",
      "pain": "the specific pain/desire this niche has",
      "angleType": "pain|outcome|social-proof|curiosity|comparison|urgency|identity|contrarian",
      "angle": "the scroll-stopping hook angle for THIS niche, written as the actual opening line (specific, benefit-led, no invented numbers)",
      "format": "ugc|tv-spot|hyper-motion|unboxing|product-review|demo|tutorial|cinematic|wild-card",
      "videoPrompt": "a vivid, specific text-to-video prompt for this niche's ad (model-agnostic) — REQUIRED, never empty",
      "outreach": "a short, human cold-outreach DM or email to reach this audience / a creator for it"
    }
  ],
  "report": "a 5-7 line strategist summary: which niches, why they convert, the angle/format mix and WHY each angle type was chosen, and the next steps"
}`;

  const res = await callAIJSON<Partial<AdPlan>>(ask, {
    system: BRAIN,
    maxTokens: 3000,
    json: true,
    model: process.env.CLAUDE_CLI_MODEL || undefined,
  });
  if (!res || !Array.isArray(res.niches) || res.niches.length === 0) {
    throw new Error('[ad-engine] Opus no devolvió nichos válidos.');
  }
  const niches: AdNiche[] = res.niches.slice(0, n).map((x) => {
    const name = String(x?.name || '').trim() || 'Niche';
    const audience = String(x?.audience || '').trim();
    const angle = String(x?.angle || '').trim();
    const angleType = String(x?.angleType || '').trim();
    const format = String(x?.format || 'ugc').trim().toLowerCase();
    // videoPrompt MUST be non-empty — generation charges on submit, so an empty prompt
    // would burn money on a junk job. If Opus omitted it, synthesize one from the niche's
    // own strategy fields rather than dropping the niche (its report/outreach still matter).
    let videoPrompt = String(x?.videoPrompt || '').trim();
    if (!videoPrompt) {
      videoPrompt = [
        `A short-form ${format} video ad for ${ctx.name}`,
        audience ? `aimed at ${audience}` : '',
        angle ? `leading with the hook: ${angle}` : '',
        `on-brand, scroll-stopping, vertical.`,
      ].filter(Boolean).join(', ');
    }
    return {
      name,
      audience,
      pain: String(x?.pain || '').trim(),
      angle,
      angleType,
      format,
      videoPrompt,
      outreach: String(x?.outreach || '').trim(),
    };
  });
  return { niches, report: String(res.report || '').trim() };
}
